# Generated by Django 3.2.7 on 2021-10-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='')),
                ('success', models.CharField(blank=True, max_length=255, null=True, verbose_name='')),
                ('message', models.CharField(blank=True, max_length=255, null=True, verbose_name='')),
                ('class_ai', models.IntegerField(blank=True, default=0, null=True, verbose_name='')),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=5, null=True, verbose_name='')),
                ('request_timestamp', models.IntegerField(blank=True, null=True, verbose_name='')),
                ('response_timestamp', models.IntegerField(blank=True, null=True, verbose_name='')),
            ],
        ),
    ]
