# Generated by Django 3.2.7 on 2021-10-09 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysismodel',
            name='class_ai',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='analysismodel',
            name='confidence',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='analysismodel',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='analysismodel',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='analysismodel',
            name='request_timestamp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysismodel',
            name='response_timestamp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysismodel',
            name='success',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
