# Generated by Django 3.2.7 on 2021-10-09 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20211009_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysismodel',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
